### PR TITLE
Update to v3.75.3

### PR DESCRIPTION
**Pull request by yann-soubeyrand**

### CODE REVIEW

**Comment by yann-soubeyrand** [comment]
I guess I'll need some help ;-)

**Comment by charlag** [comment]
systemjs-hmr is not in the generated JS sources.
We don't need it for the build but then we don't need to try to install it either.
So you should either add it to generated sources somehow or remove from build dependencies.

**Comment by jkonecny12** [comment]
Thanks a lot for working on this. Especially [Fedora SilverBlue](https://silverblue.fedoraproject.org/) and other distros using flatpak as the main source of applications will thank you for that ;)!

**Comment by yann-soubeyrand** [comment]
Obsoleted by https://github.com/flathub/com.tutanota.Tutanota/pull/15.

**Pull request closed without merging**
