### PR TITLE
WIP: 3.76.10 

### PR DESCRIPTION
**Pull request by rany2**

### CODE REVIEW

**Comment by analotia** [comment]
bot, build

**Comment by analotia** [comment]
bot, build

**Comment by analotia** [comment]
bot, build

**Comment by analotia** [comment]
bot, build

**Comment by charlag** [comment]
Check #9, it should work but we need to build keytar on our own

**Comment by analotia** [comment]
@charlag Would that fix the electron issue?

**Comment by charlag** [comment]
Which issue?

**Comment by analotia** [comment]
@charlag 

```
> keytar@6.0.1 install /run/build/tutanota/node_modules/keytar
> prebuild-install || node-gyp rebuild
prebuild-install WARN install getaddrinfo EAI_AGAIN github.com github.com:443
make: Entering directory '/run/build/tutanota/node_modules/keytar/build'
  CXX(target) Release/obj.target/keytar/src/async.o
  CXX(target) Release/obj.target/keytar/src/main.o
  CXX(target) Release/obj.target/keytar/src/keytar_posix.o
  SOLINK_MODULE(target) Release/obj.target/keytar.node
  COPY Release/keytar.node
make: Leaving directory '/run/build/tutanota/node_modules/keytar/build'
[?25l[            ......] | postinstall:xhr2: sill doSerial postinstall 8280
[?25h
> core-js@2.6.10 postinstall /run/build/tutanota/node_modules/core-js
> node postinstall || echo "ignore"
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 
Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
> core-js@3.6.5 postinstall /run/build/tutanota/node_modules/global-agent/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
> ejs@3.1.3 postinstall /run/build/tutanota/node_modules/ejs
> node --harmony ./postinstall.js
Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)
[?25l[            ......] / postinstall:resolve: info lifecycle resolve@1.15.1~posti
[            ......] \ postinstall:babel-plugin-transform-es2015-modules-common
[            ......] \ postinstall:xdg-basedir: info lifecycle xdg-basedir@4.0.
[?25h
> electron@9.0.5 postinstall /run/build/tutanota/node_modules/electron
> node install.js
RequestError: getaddrinfo EAI_AGAIN github.com github.com:443
    at ClientRequest.request.once.error (/run/build/tutanota/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:203:15)
    at ClientRequest.origin.emit.args (/run/build/tutanota/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[?25l[            ......] \ postinstall: info lifecycle electron@9.0.5~postinstall:
[            ......] \ postinstall: info lifecycle electron@9.0.5~postinstall:
[            ......] \ postinstall: info lifecycle electron@9.0.5~postinstall:
[?25hnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@9.0.5 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@9.0.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /run/build/tutanota/npm-cache/_logs/2020-10-01T12_03_30_543Z-debug.log
```

**Comment by analotia** [comment]
The `dist-generate-sources.json` and `generated-sources.json` are okay AFAIK

**Comment by analotia** [comment]
I have a feeling `package-lock.json` is being overwritten somehow

**Comment by charlag** [comment]
We need to build keytar on our own and not download anything. I think that's the issue.

**Comment by analotia** [comment]
but keytar is already downloaded by flatpak-builder

**Comment by charlag** [comment]
Keytar has a native part, I'm not sure if `dist-generated-sources` handles it or not

**Comment by analotia** [comment]
isn't that `libsecret`?

**Comment by TheEvilSkeleton** [comment]
Should I close my issue since we are continuing here?

**Comment by analotia** [comment]
@TheEvilSkeleton I think so

**Comment by charlag** [comment]
Keytar needs libsecret for a build, yes, but it has it's own C++ code to talk wrap libsecret

**Comment by analotia** [comment]
@charlag I didn't know that. Thanks for telling me. I guess that's a new dependency

**Comment by TheEvilSkeleton** [comment]
@ganthern feel free to join us.

**Comment by TheEvilSkeleton** [comment]
Should we contact the npm developers and ask for their support?

**Comment by analotia** [comment]
@charlag Nevermind it compiles itself when you do a `npm install`

**Comment by charlag** [comment]
I'm going to unsubscribe from this, sorry, it's too spammy, ganthern is already looking into this and I would leave this to him

**Comment by analotia** [comment]
I really should make one big commit lol

**Pull request closed without merging**
