### PR TITLE
Update runtime version to 19.08

### PR DESCRIPTION
**Pull request by alatiera**
I know this keeps the app still outdated, but at least it should make future work on updating it easier.

### CODE REVIEW

**Comment by charlag** [comment]
Hi
This would be awesome to merge although there are some metadata problems which I started to fix in another PR and we need to address that first I guess.

**Comment by charlag** [comment]
I will try to merge #4, last few builds even succeeded and then we can rebase this PR on top of it

**Comment by charlag** [comment]
@alatiera can you please rebase it on master? I merged #4 
Otherwise I'll do it later

**Comment by alatiera** [comment]
Sure I can, though #4 doesn't seem to have been merged yet over here.

**Comment by charlag** [comment]
Ah,I forgot to push, my bad, will do tomorrow.

**Comment by alatiera** [comment]
Looks like the test build is launching and running as expected.

**Comment by charlag** [comment]
Cool thanks a lot.

**Pull request merged**
